# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
swift_version = "3.0"

# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

target 'TheBooks' do
	pod "PromiseKit", "~> 4.0"
	pod "SwiftKeychainWrapper", "~> 3.0"
	pod "BKPasscodeView", "~> 0.1.2"
end
